version: '2'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile_web
    restart: on-failure
    volumes:
        - ./data/lime_survey/html:/code
        - ./data/logs/web:/var/log/nginx
        - ./build/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
        - 80
    links:
        - lime
        - reindeer
    command: dockerize -wait http://reindeer:3000/reindeer/robots.txt -wait tcp://lime:9000 bash -c "nginx -g 'daemon off;'"
  lime:
    restart: on-failure
    build: 
        context: .
        dockerfile: Dockerfile_lime_survey
    volumes:
        - ./data/lime_survey/html:/code
        - ./data/lime_survey/downloads:/tmp/downloads
        - ./build/web:/mnt/web:ro
        - ./build/lime:/docker:ro
    env_file: .dockerenv
    ports:
        - 9000
    links:
        - db
    command: dockerize -wait tcp://db:5432 php-fpm
  db: 
    restart: on-failure
    image: postgres:9.5
    volumes:
        - ./data/db/data:/var/lib/postgresql/data
    env_file: .dockerenv
    ports:
        - 5432
  reindeer:
    restart: on-failure:10
    build: 
        context: .
        dockerfile: Dockerfile_reindeer
    env_file: .dockerenv
    volumes:
        - ./:/home/app
        - /home/app/data    # hide contents of data from container
        - ./build/reindeer:/docker:ro
        - ./data/lime_survey:/lime_survey
    ports:
        - 3000
    links:
        - db
    command: dockerize -wait tcp://db:5432 ./bin/thin-start
