version: '2'
services:
  web:
    image: nginx:1.11.1
    restart: on-failure:10
    volumes:
        - ./data/lime_survey/html:/code
        - ./data/logs/web:/var/log/nginx
        - ./build/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
        - 80
    links:
        - lime
        - reindeer
  lime:
    restart: on-failure:10
    build: 
        context: .
        dockerfile: Dockerfile_lime_survey
    volumes:
        - ./data/lime_survey/html:/code
        - ./data/lime_survey/downloads:/tmp/downloads
        - ./build/lime:/docker:ro
    env_file: .dockerenv
    environment:
        # Version of lime_survey to download
        LIME_BIN_URL: "https://github.com/LimeSurvey/LimeSurvey/archive/2.06_plus_160123.tar.gz"
        # SHA256 for verifying validity of lime tar.gz
        LIME_SHA256: 499f8557701175d2ee3586184b6f88fa755ebf1113e29da3e8e3b2a65f263097
    links:
        - db
    ports:
        - 9000
  db: 
    restart: on-failure:10
    image: postgres:9.5.3
    volumes:
        - ./data/db/data:/var/lib/postgresql/data
    env_file: .dockerenv
    ports:
        - 5432
  reindeer:
    restart: on-failure:10
    build: 
        context: .
        dockerfile: Dockerfile_reindeer
    env_file: .dockerenv
    volumes:
        - ./:/home/app
        - /home/app/data    # hide contents of data from container
        - ./build/reindeer:/docker:ro
        - ./data/lime_survey:/lime_survey
    ports:
        - 3000
    links:
        - db
