version: '2'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile_web
    restart: on-failure
    volumes:
        - ./data/web:/var/www/html
        - ./data/logs/web:/var/log/nginx
        - ./build/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
        - lime
    ports:
        - 80
    env_file: ./data/dockerenv
    links:
        - lime
        - reindeer
    command: dockerize -wait http://reindeer:3000/reindeer/robots.txt -wait tcp://lime:9000 bash -c "nginx -g 'daemon off;'"
  lime:
    restart: on-failure
    build: 
        context: .
        dockerfile: Dockerfile_lime_survey
    volumes:
        - ./data/config.php:/var/www/html/survey/application/config/config.php
        - ./build/web:/mnt/web:ro
        - ./build/lime:/docker:ro
    env_file: ./data/dockerenv
    ports:
        - 9000
    links:
        - db
    command: dockerize -wait tcp://db:5432 php-fpm
  db: 
    restart: on-failure
    image: postgres:9.5
    volumes:
        - ./data/db/data:/var/lib/postgresql/data
    env_file: ./data/dockerenv
    ports:
        - 5432
  reindeer:
    restart: on-failure:10
    build: 
        context: .
        dockerfile: Dockerfile_reindeer
    env_file: ./data/dockerenv
    volumes:
        - ./:/home/app
        - ./data/settings.yml:/home/app/config/settings.yml
        - ./data/database.yml:/home/app/config/database.yml
        - /home/app/data    # hide contents of data from container
        - ./build/reindeer:/docker:ro
        - ./data/reindeer/public:/home/app/public/data
    ports:
        - 3000
    links:
        - db
    command: dockerize -wait tcp://db:5432 ./bin/thin-start
