require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/badging_dates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BadgingDate. As you add validations to BadgingDate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BadgingDate.create! valid_attributes
      get badging_dates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      badging_date = BadgingDate.create! valid_attributes
      get badging_date_url(badging_date)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_badging_date_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      badging_date = BadgingDate.create! valid_attributes
      get edit_badging_date_url(badging_date)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BadgingDate" do
        expect {
          post badging_dates_url, params: { badging_date: valid_attributes }
        }.to change(BadgingDate, :count).by(1)
      end

      it "redirects to the created badging_date" do
        post badging_dates_url, params: { badging_date: valid_attributes }
        expect(response).to redirect_to(badging_date_url(BadgingDate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BadgingDate" do
        expect {
          post badging_dates_url, params: { badging_date: invalid_attributes }
        }.to change(BadgingDate, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post badging_dates_url, params: { badging_date: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested badging_date" do
        badging_date = BadgingDate.create! valid_attributes
        patch badging_date_url(badging_date), params: { badging_date: new_attributes }
        badging_date.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the badging_date" do
        badging_date = BadgingDate.create! valid_attributes
        patch badging_date_url(badging_date), params: { badging_date: new_attributes }
        badging_date.reload
        expect(response).to redirect_to(badging_date_url(badging_date))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        badging_date = BadgingDate.create! valid_attributes
        patch badging_date_url(badging_date), params: { badging_date: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested badging_date" do
      badging_date = BadgingDate.create! valid_attributes
      expect {
        delete badging_date_url(badging_date)
      }.to change(BadgingDate, :count).by(-1)
    end

    it "redirects to the badging_dates list" do
      badging_date = BadgingDate.create! valid_attributes
      delete badging_date_url(badging_date)
      expect(response).to redirect_to(badging_dates_url)
    end
  end
end
