 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fom_remeds", type: :request do
  
  # FomRemed. As you add validations to FomRemed, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FomRemed.create! valid_attributes
      get fom_remeds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fom_remed = FomRemed.create! valid_attributes
      get fom_remed_url(fom_remed)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fom_remed_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      fom_remed = FomRemed.create! valid_attributes
      get edit_fom_remed_url(fom_remed)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FomRemed" do
        expect {
          post fom_remeds_url, params: { fom_remed: valid_attributes }
        }.to change(FomRemed, :count).by(1)
      end

      it "redirects to the created fom_remed" do
        post fom_remeds_url, params: { fom_remed: valid_attributes }
        expect(response).to redirect_to(fom_remed_url(FomRemed.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FomRemed" do
        expect {
          post fom_remeds_url, params: { fom_remed: invalid_attributes }
        }.to change(FomRemed, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post fom_remeds_url, params: { fom_remed: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fom_remed" do
        fom_remed = FomRemed.create! valid_attributes
        patch fom_remed_url(fom_remed), params: { fom_remed: new_attributes }
        fom_remed.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fom_remed" do
        fom_remed = FomRemed.create! valid_attributes
        patch fom_remed_url(fom_remed), params: { fom_remed: new_attributes }
        fom_remed.reload
        expect(response).to redirect_to(fom_remed_url(fom_remed))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        fom_remed = FomRemed.create! valid_attributes
        patch fom_remed_url(fom_remed), params: { fom_remed: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fom_remed" do
      fom_remed = FomRemed.create! valid_attributes
      expect {
        delete fom_remed_url(fom_remed)
      }.to change(FomRemed, :count).by(-1)
    end

    it "redirects to the fom_remeds list" do
      fom_remed = FomRemed.create! valid_attributes
      delete fom_remed_url(fom_remed)
      expect(response).to redirect_to(fom_remeds_url)
    end
  end
end
