require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/precep_meetings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PrecepMeeting. As you add validations to PrecepMeeting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PrecepMeeting.create! valid_attributes
      get precep_meetings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      precep_meeting = PrecepMeeting.create! valid_attributes
      get precep_meeting_url(precep_meeting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_precep_meeting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      precep_meeting = PrecepMeeting.create! valid_attributes
      get edit_precep_meeting_url(precep_meeting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrecepMeeting" do
        expect {
          post precep_meetings_url, params: { precep_meeting: valid_attributes }
        }.to change(PrecepMeeting, :count).by(1)
      end

      it "redirects to the created precep_meeting" do
        post precep_meetings_url, params: { precep_meeting: valid_attributes }
        expect(response).to redirect_to(precep_meeting_url(PrecepMeeting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrecepMeeting" do
        expect {
          post precep_meetings_url, params: { precep_meeting: invalid_attributes }
        }.to change(PrecepMeeting, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post precep_meetings_url, params: { precep_meeting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested precep_meeting" do
        precep_meeting = PrecepMeeting.create! valid_attributes
        patch precep_meeting_url(precep_meeting), params: { precep_meeting: new_attributes }
        precep_meeting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the precep_meeting" do
        precep_meeting = PrecepMeeting.create! valid_attributes
        patch precep_meeting_url(precep_meeting), params: { precep_meeting: new_attributes }
        precep_meeting.reload
        expect(response).to redirect_to(precep_meeting_url(precep_meeting))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        precep_meeting = PrecepMeeting.create! valid_attributes
        patch precep_meeting_url(precep_meeting), params: { precep_meeting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested precep_meeting" do
      precep_meeting = PrecepMeeting.create! valid_attributes
      expect {
        delete precep_meeting_url(precep_meeting)
      }.to change(PrecepMeeting, :count).by(-1)
    end

    it "redirects to the precep_meetings list" do
      precep_meeting = PrecepMeeting.create! valid_attributes
      delete precep_meeting_url(precep_meeting)
      expect(response).to redirect_to(precep_meetings_url)
    end
  end
end
